### ISSUE TITLE
build fails because of missing dep

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/bw_processing#12]
[Travis build](https://travis-ci.org/github/brightway-lca/bw_processing) failed.

Here's a hint on why:

```python
...
/lib/python3.9/site-packages/bw_processing/io_helpers.py", line 2, in <module>

    from fs.base import FS

ModuleNotFoundError: No module named 'fs'
```

but the Azure pipeline went through.

Do we:

- [ ] keep azure pipelines only and remove the .travis config
- [ ] keep both, and fix the travis one
?

**Comment by cmutel** [comment]
We no longer use travis, and I have delete the travis config from the repo.
