### ISSUE TITLE
Refactor `datapackage.py`

### ISSUE THREAD

**Issue by nikolaj-funartech** [brightway-lca/bw_processing#37]
`Datapackage` has several `add_xxx` methods that could be refactored for make the code shorter and easier to maintain.

**Comment by cmutel** [comment]
@nikolaj-funartech Can you give a little more detail here?

**Comment by nikolaj-funartech** [comment]
@cmutel Very basic refactoring: all the `add_xxx` methods are doing very similar things. The idea is to create sub routines (methods) that do the common work.
